version: "3.7"

services:
  VIED:
    image: vied_tester1
#    cap-add:
#      - ALL
    networks:
      macvlan_net:
        ipv4_address: 10.102.76.201
    container_name: TESTE_JP1

networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: 10.102.76.0/23
          gateway: 10.102.76.1
